***DAY 1***

In [1]:
import pandas as pd
data={
    "Name":["Amit","Rohit","Sneha","Priya","Karan"],
    "Age":[20,None,19,22,20],
    "Marks":[78,85,None,67,88]
}
df=pd.DataFrame(data)
df

    Name   Age  Marks
0   Amit  20.0   78.0
1  Rohit   NaN   85.0
2  Sneha  19.0    NaN
3  Priya  22.0   67.0
4  Karan  20.0   88.0

# To know the shape

In [2]:
df.shape

(5, 3)

# To Know the column

In [3]:
df.columns

Index(['Name', 'Age', 'Marks'], dtype='str')

# To know all info

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    5 non-null      str
 1   Age     4 non-null      float64
 2   Marks   4 non-null      float64
dtypes: float64(2), str(1)
memory usage: 252.0 bytes

# To Describe the data

In [5]:
df.describe()

             Age      Marks
count   4.000000   4.000000
mean   20.250000  79.500000
std     1.258306   9.327379
min    19.000000  67.000000
25%    19.750000  75.250000
50%    20.000000  81.500000
75%    20.500000  85.750000
max    22.000000  88.000000

# 1.Select one column

In [6]:
df["Name"]

0     Amit
1    Rohit
2    Sneha
3    Priya
4    Karan
Name: Name, dtype: str

# 2. Select Multiple columns

In [7]:
df[["Name","Marks","Age"]]

    Name  Marks   Age
0   Amit   78.0  20.0
1  Rohit   85.0   NaN
2  Sneha    NaN  19.0
3  Priya   67.0  22.0
4  Karan   88.0  20.0

# 3. Selecting rows with iloc[]

In [8]:
# First Row
df.iloc[0]

Name     Amit
Age      20.0
Marks    78.0
Name: 0, dtype: object

# 4. Selecting Specific column and row

In [9]:
df.iloc[0,2]

np.float64(78.0)

In [10]:
df.iloc[2,0]

'Sneha'

# 5. Select rows and columns together

In [11]:
df.iloc[0:3,0:2]

    Name   Age
0   Amit  20.0
1  Rohit   NaN
2  Sneha  19.0

# 6. Usinf loc[]

In [12]:
df.loc[:,["Name","Marks"]]

    Name  Marks
0   Amit   78.0
1  Rohit   85.0
2  Sneha    NaN
3  Priya   67.0
4  Karan   88.0

In [13]:
df.loc[0]

Name     Amit
Age      20.0
Marks    78.0
Name: 0, dtype: object

# Filtering the data

In [14]:
df["Marks"]>80

0    False
1     True
2    False
3    False
4     True
Name: Marks, dtype: bool

In [15]:
df[df["Marks"]>80]

    Name   Age  Marks
1  Rohit   NaN   85.0
4  Karan  20.0   88.0

In [16]:
df[df["Marks"]<80]

    Name   Age  Marks
0   Amit  20.0   78.0
3  Priya  22.0   67.0

In [17]:
df[df["Marks"]==85]

    Name  Age  Marks
1  Rohit  NaN   85.0

# Multiple Condition

In [18]:
df[(df["Marks"]>80) | (df["Marks"]<22)]

    Name   Age  Marks
1  Rohit   NaN   85.0
4  Karan  20.0   88.0

# To Add a new column

In [19]:
df["City"]=["Delhi","Mumbai","Delhi","Pune","Delhi"]
df

    Name   Age  Marks    City
0   Amit  20.0   78.0   Delhi
1  Rohit   NaN   85.0  Mumbai
2  Sneha  19.0    NaN   Delhi
3  Priya  22.0   67.0    Pune
4  Karan  20.0   88.0   Delhi

# Create a column using the calculation

In [20]:
df["Result"]=df["Marks"]>=40
df

    Name   Age  Marks    City  Result
0   Amit  20.0   78.0   Delhi    True
1  Rohit   NaN   85.0  Mumbai    True
2  Sneha  19.0    NaN   Delhi   False
3  Priya  22.0   67.0    Pune    True
4  Karan  20.0   88.0   Delhi    True

# Rename the column

In [21]:
df.rename(columns={"Marks":"Score"},inplace=True)
df

    Name   Age  Score    City  Result
0   Amit  20.0   78.0   Delhi    True
1  Rohit   NaN   85.0  Mumbai    True
2  Sneha  19.0    NaN   Delhi   False
3  Priya  22.0   67.0    Pune    True
4  Karan  20.0   88.0   Delhi    True

# To Delete the column

In [22]:
df.drop("City",axis=1,inplace=True)  #axis=1 is column,axis=0 is for row

In [23]:
df

    Name   Age  Score  Result
0   Amit  20.0   78.0    True
1  Rohit   NaN   85.0    True
2  Sneha  19.0    NaN   False
3  Priya  22.0   67.0    True
4  Karan  20.0   88.0    True

# To Sort The Values

In [24]:
df.sort_values("Score")

    Name   Age  Score  Result
3  Priya  22.0   67.0    True
0   Amit  20.0   78.0    True
1  Rohit   NaN   85.0    True
4  Karan  20.0   88.0    True
2  Sneha  19.0    NaN   False

# In Descending Order

In [25]:
df.sort_values("Score",ascending=False)

    Name   Age  Score  Result
4  Karan  20.0   88.0    True
1  Rohit   NaN   85.0    True
0   Amit  20.0   78.0    True
3  Priya  22.0   67.0    True
2  Sneha  19.0    NaN   False

# Sort By multiple columns

In [26]:
df.sort_values(["Age","Score"])

    Name   Age  Score  Result
2  Sneha  19.0    NaN   False
0   Amit  20.0   78.0    True
4  Karan  20.0   88.0    True
3  Priya  22.0   67.0    True
1  Rohit   NaN   85.0    True

# **I am adding city column**

In [27]:
df["City"]=["Delhi","Mumbai","Delhi","Pune","Delhi"]

In [28]:
df

    Name   Age  Score  Result    City
0   Amit  20.0   78.0    True   Delhi
1  Rohit   NaN   85.0    True  Mumbai
2  Sneha  19.0    NaN   False   Delhi
3  Priya  22.0   67.0    True    Pune
4  Karan  20.0   88.0    True   Delhi

# This function tells how many time the value is occuured

In [29]:
df["City"].value_counts()

City
Delhi     3
Mumbai    1
Pune      1
Name: count, dtype: int64

# To Find the missing value

In [30]:
df.isnull()

    Name    Age  Score  Result   City
0  False  False  False   False  False
1  False   True  False   False  False
2  False  False   True   False  False
3  False  False  False   False  False
4  False  False  False   False  False

# To Count the missing value

In [31]:
df.isnull().sum()

Name      0
Age       1
Score     1
Result    0
City      0
dtype: int64

In [32]:
df.isna().sum()

Name      0
Age       1
Score     1
Result    0
City      0
dtype: int64

# To drop missing values

In [33]:
# df.dropna()

# To Fill The Missing value

In [34]:
# df["Age"]=df["Age"].fillna(20)

In [35]:
# df["Score"]=df["Score"].fillna(90)
df

    Name   Age  Score  Result    City
0   Amit  20.0   78.0    True   Delhi
1  Rohit   NaN   85.0    True  Mumbai
2  Sneha  19.0    NaN   False   Delhi
3  Priya  22.0   67.0    True    Pune
4  Karan  20.0   88.0    True   Delhi

# Filling the missing value by "mean"

In [36]:
# df["Age"]=df["Age"].fillna(df["Age"].mean())

df

    Name   Age  Score  Result    City
0   Amit  20.0   78.0    True   Delhi
1  Rohit   NaN   85.0    True  Mumbai
2  Sneha  19.0    NaN   False   Delhi
3  Priya  22.0   67.0    True    Pune
4  Karan  20.0   88.0    True   Delhi

In [37]:
# df["Score"]=df["Score"].fillna(df["Score"].mean())
df

    Name   Age  Score  Result    City
0   Amit  20.0   78.0    True   Delhi
1  Rohit   NaN   85.0    True  Mumbai
2  Sneha  19.0    NaN   False   Delhi
3  Priya  22.0   67.0    True    Pune
4  Karan  20.0   88.0    True   Delhi

# Filling the missing value by "Median"

In [38]:
df["Age"]=df["Age"].fillna(df["Age"].median())
df["Score"]=df["Score"].fillna(df["Score"].median())
df

    Name   Age  Score  Result    City
0   Amit  20.0   78.0    True   Delhi
1  Rohit  20.0   85.0    True  Mumbai
2  Sneha  19.0   81.5   False   Delhi
3  Priya  22.0   67.0    True    Pune
4  Karan  20.0   88.0    True   Delhi