In [1]:
import pandas as pd
data={
    "Name":["  Amit","Rohit","Sneha","Priya","Amit","Ankit"],
    "City":["Delhi","delhi","Mumbai","Delhi","Delhi","mumbai"],
    "Marks":[78,85,92,67,78,87]

}
df=pd.DataFrame(data)
df

     Name    City  Marks
0    Amit   Delhi     78
1   Rohit   delhi     85
2   Sneha  Mumbai     92
3   Priya   Delhi     67
4    Amit   Delhi     78
5   Ankit  mumbai     87

# To Find The Duplicate Value

In [2]:
df.duplicated().sum()

np.int64(0)

# To Remove The Duplicate Value

In [3]:
df.drop_duplicates(inplace=True)
df

     Name    City  Marks
0    Amit   Delhi     78
1   Rohit   delhi     85
2   Sneha  Mumbai     92
3   Priya   Delhi     67
4    Amit   Delhi     78
5   Ankit  mumbai     87

# Inconsistent Values

In [4]:
df["City"].value_counts()

City
Delhi     3
delhi     1
Mumbai    1
mumbai    1
Name: count, dtype: int64

# Convert text to lower case

In [5]:
# df["City"]=df["City"].str.lower()
df

     Name    City  Marks
0    Amit   Delhi     78
1   Rohit   delhi     85
2   Sneha  Mumbai     92
3   Priya   Delhi     67
4    Amit   Delhi     78
5   Ankit  mumbai     87

# Convert text to upper case

In [6]:
# df["City"]=df["City"].str.upper()
df

     Name    City  Marks
0    Amit   Delhi     78
1   Rohit   delhi     85
2   Sneha  Mumbai     92
3   Priya   Delhi     67
4    Amit   Delhi     78
5   Ankit  mumbai     87

# To Replace The value

In [7]:
df["City"]=df["City"].replace("delhi","Delhi")
df

     Name    City  Marks
0    Amit   Delhi     78
1   Rohit   Delhi     85
2   Sneha  Mumbai     92
3   Priya   Delhi     67
4    Amit   Delhi     78
5   Ankit  mumbai     87

# To Replace the multiple value

In [8]:
df["City"]=df["City"].replace({"delhi":"Delhi",
"mumbai":"Mumbai"})
df

     Name    City  Marks
0    Amit   Delhi     78
1   Rohit   Delhi     85
2   Sneha  Mumbai     92
3   Priya   Delhi     67
4    Amit   Delhi     78
5   Ankit  Mumbai     87

# To Remove The extra spaces

In [9]:
df["City"]=df["City"].str.strip()
df

     Name    City  Marks
0    Amit   Delhi     78
1   Rohit   Delhi     85
2   Sneha  Mumbai     92
3   Priya   Delhi     67
4    Amit   Delhi     78
5   Ankit  Mumbai     87

In [10]:
df["Name"]=df["Name"].str.strip()
df

    Name    City  Marks
0   Amit   Delhi     78
1  Rohit   Delhi     85
2  Sneha  Mumbai     92
3  Priya   Delhi     67
4   Amit   Delhi     78
5  Ankit  Mumbai     87