DAY 3

In [1]:
import pandas as pd
data={
    "Name":["Amit","Rohit","Sneha","Priya","Karan"],
    "Age":[20,21,19,22,20],
    "Marks":[78,85,92,67,88]
}
df=pd.DataFrame(data)
df

    Name  Age  Marks
0   Amit   20     78
1  Rohit   21     85
2  Sneha   19     92
3  Priya   22     67
4  Karan   20     88

# 1.apply(),

In [2]:
df["Marks"]=df["Marks"].apply(lambda x:x+5) # Lammda means take x and return x+5 here
df

    Name  Age  Marks
0   Amit   20     83
1  Rohit   21     90
2  Sneha   19     97
3  Priya   22     72
4  Karan   20     93

In [3]:
def grade(Marks):
    if Marks>=90:
        return "A"
    elif Marks>=80:
        return "B"
    elif Marks>=70:
        return "C"
    else:
        return "D"

In [4]:
df["Grade"]=df["Marks"].apply(grade)
df

    Name  Age  Marks Grade
0   Amit   20     83     B
1  Rohit   21     90     A
2  Sneha   19     97     A
3  Priya   22     72     C
4  Karan   20     93     A

# 2.map

In [5]:
df["Gender"]=["M","M","F","F","M"]

In [6]:
df["Gender"]=df["Gender"].map({"M":"Male","F":"Female"})
df

    Name  Age  Marks Grade  Gender
0   Amit   20     83     B    Male
1  Rohit   21     90     A    Male
2  Sneha   19     97     A  Female
3  Priya   22     72     C  Female
4  Karan   20     93     A    Male

# 3.replace # Also used to change the value as we seen in Day2 lecture

# 4.groupby()

In [7]:
df=pd.read_csv(r"C:\Users\ankit\OneDrive\Desktop\Pandas\eployee.csv")
df

,Employee_ID,Name,Department,Gender,Salary,Experience,Performance,Grade,Salary Category,Experience Level
0,2001,Rahul,IT,Male,40000,2,82,B,Medium,Mid-Level
1,2002,Priya,HR,Female,52000,3,91,A,Medium,Mid-Level
2,2003,Aman,Finance,Male,38000,1,68,D,low,Fresher
3,2004,Neha,IT,Female,75000,5,95,A,High,senior
4,2005,Rohit,Sales,Male,42000,2,76,C,Medium,Mid-Level
5,2006,Simran,HR,Female,61000,4,88,B,Medium,Mid-Level
6,2007,Arjun,Finance,Male,82000,6,93,A,High,senior
7,2008,Kavya,IT,Female,39000,1,72,C,low,Fresher
8,2009,Vikas,Sales,Male,68000,4,85,B,Medium,Mid-Level
9,2010,Pooja,HR,Female,47000,2,79,C,Medium,Mid-Level
10,2011,Deepak,Finance,Male,55000,3,87,B,Medium,Mid-Level
11,2012,Nisha,IT,Female,92000,7,97,A,High,senior
12,2013,Manish,Sales,Male,36000,1,65,D,low,Fresher
13,2014,Riya,HR,Female,78000,5,90,A,High,senior
14,2015,Karan,Finance,Male,43000,2,74,C,Medium,Mid-Level
15,2016,Anjali,IT,Female,64000,4,84,B,Medium,Mid-Level
16,2017,Sachin,Sales,Male,59000,3,81,B,Medium,Mid-Level
17,2018,Meena,HR,Female,35000,1,69,D,low,Fresher
18,2019,Varun,IT,Male,88000,6,92,A,High,senior
19,2020,Isha,Finance,Female,70000,5,89,B,Medium,senior

In [8]:
df.groupby("Department")["Salary"].mean()

Department
Finance    57600.000000
HR         54600.000000
IT         66333.333333
Sales      51250.000000
Name: Salary, dtype: float64

In [9]:
df.groupby("Department")["Salary"].max()

Department
Finance    82000
HR         78000
IT         92000
Sales      68000
Name: Salary, dtype: int64

# Multiple Calculation

In [26]:
df.groupby("Department")["Salary"].agg(['mean','max','min','count'])

                    mean    max    min  count
Department
Finance     57600.000000  82000  38000      5
HR          54600.000000  78000  35000      5
IT          66333.333333  92000  39000      6
Sales       51250.000000  68000  36000      4

Different calculation for different columns

In [11]:
df.groupby("Department").agg({"Salary":["mean","max"],
                              "Performance":["mean","max"],
                              "Experience":"mean"})

                  Salary        Performance     Experience
                    mean    max        mean max       mean
Department
Finance     57600.000000  82000       82.20  93   3.400000
HR          54600.000000  78000       83.40  91   3.000000
IT          66333.333333  92000       87.00  97   4.166667
Sales       51250.000000  68000       76.75  85   2.500000

Rename the results

In [12]:
result=df.groupby("Department").agg(
    Average_Salary=("Salary","mean"),
    Maximum_Salary=("Salary","max"),
    Average_Performance=("Performance","mean"),
    Maximum_Performance=("Performance","max"),
    Average_Experience=("Experience","mean")

)
result

,Average_Salary,Maximum_Salary,Average_Performance,Maximum_Performance,Average_Experience
Department,,,,,
Finance,57600.000000,82000,82.20,93,3.400000
HR,54600.000000,78000,83.40,91,3.000000
IT,66333.333333,92000,87.00,97,4.166667
Sales,51250.000000,68000,76.75,85,2.500000

# Merge Function

In [13]:
data=pd.read_csv(r"C:\Users\ankit\OneDrive\Desktop\employee_bonuses.csv")
data

    Employee_ID  Bonus_Percentage  Bonus_Amount Promotion_Eligible
0          2001                 5          2250                 No
1          2002                 8          4160                Yes
2          2003                 3          1140                 No
3          2004                10          7500                Yes
4          2005                 6          2520                 No
5          2006                 9          5490                Yes
6          2007                12          9840                Yes
7          2008                 4          1560                 No
8          2009                 8          5440                Yes
9          2010                 5          2350                 No
10         2011                 7          3850                Yes
11         2012                15         13800                Yes
12         2013                 2           720                 No
13         2014                10          7800                Yes
14         2015                 4          1720                 No
15         2016                 8          5120                Yes
16         2017                 7          4130                Yes
17         2018                 3          1050                 No
18         2019                11          9680                Yes
19         2020                 9          6300                Yes

In [14]:
result=pd.merge(
    df,data,
    on="Employee_ID"
)
result

,Employee_ID,Name,Department,Gender,Salary,Experience,Performance,Grade,Salary Category,Experience Level,Bonus_Percentage,Bonus_Amount,Promotion_Eligible
0,2001,Rahul,IT,Male,40000,2,82,B,Medium,Mid-Level,5,2250,No
1,2002,Priya,HR,Female,52000,3,91,A,Medium,Mid-Level,8,4160,Yes
2,2003,Aman,Finance,Male,38000,1,68,D,low,Fresher,3,1140,No
3,2004,Neha,IT,Female,75000,5,95,A,High,senior,10,7500,Yes
4,2005,Rohit,Sales,Male,42000,2,76,C,Medium,Mid-Level,6,2520,No
5,2006,Simran,HR,Female,61000,4,88,B,Medium,Mid-Level,9,5490,Yes
6,2007,Arjun,Finance,Male,82000,6,93,A,High,senior,12,9840,Yes
7,2008,Kavya,IT,Female,39000,1,72,C,low,Fresher,4,1560,No
8,2009,Vikas,Sales,Male,68000,4,85,B,Medium,Mid-Level,8,5440,Yes
9,2010,Pooja,HR,Female,47000,2,79,C,Medium,Mid-Level,5,2350,No
10,2011,Deepak,Finance,Male,55000,3,87,B,Medium,Mid-Level,7,3850,Yes
11,2012,Nisha,IT,Female,92000,7,97,A,High,senior,15,13800,Yes
12,2013,Manish,Sales,Male,36000,1,65,D,low,Fresher,2,720,No
13,2014,Riya,HR,Female,78000,5,90,A,High,senior,10,7800,Yes
14,2015,Karan,Finance,Male,43000,2,74,C,Medium,Mid-Level,4,1720,No
15,2016,Anjali,IT,Female,64000,4,84,B,Medium,Mid-Level,8,5120,Yes
16,2017,Sachin,Sales,Male,59000,3,81,B,Medium,Mid-Level,7,4130,Yes
17,2018,Meena,HR,Female,35000,1,69,D,low,Fresher,3,1050,No
18,2019,Varun,IT,Male,88000,6,92,A,High,senior,11,9680,Yes
19,2020,Isha,Finance,Female,70000,5,89,B,Medium,senior,9,6300,Yes

In [15]:
employees=pd.DataFrame({
    "Employee_ID":[101,102,103,104,105],
    "Name":["Rahul","Priya","Aman","Neha","Rohit"],
    "Department ID":[1,2,1,3,2]
})

employees

   Employee_ID   Name  Department ID
0          101  Rahul              1
1          102  Priya              2
2          103   Aman              1
3          104   Neha              3
4          105  Rohit              2

In [16]:
departments=pd.DataFrame({
    "Department ID":[1,2,3],
    "Departments":["IT","HR","Finance"]
})
departments

   Department ID Departments
0              1          IT
1              2          HR
2              3     Finance

# Inner Join

In [17]:
output=pd.merge(
    employees,departments,
    on="Department ID",
    how="inner"

)
output

   Employee_ID   Name  Department ID Departments
0          101  Rahul              1          IT
1          102  Priya              2          HR
2          103   Aman              1          IT
3          104   Neha              3     Finance
4          105  Rohit              2          HR

# Left Join

In [18]:
output=pd.merge(employees,departments,
                on="Department ID",
                how="left"
    
)
output

   Employee_ID   Name  Department ID Departments
0          101  Rahul              1          IT
1          102  Priya              2          HR
2          103   Aman              1          IT
3          104   Neha              3     Finance
4          105  Rohit              2          HR

# Right Join

In [19]:
output=pd.merge(employees,departments,
                on="Department ID",
                how="right"
    
)
output.sort_values("Employee_ID")

   Employee_ID   Name  Department ID Departments
0          101  Rahul              1          IT
2          102  Priya              2          HR
1          103   Aman              1          IT
4          104   Neha              3     Finance
3          105  Rohit              2          HR

# Outer Join

In [20]:
output=pd.merge(employees,departments,
                on="Department ID",
                how="outer")
output

   Employee_ID   Name  Department ID Departments
0          101  Rahul              1          IT
1          103   Aman              1          IT
2          102  Priya              2          HR
3          105  Rohit              2          HR
4          104   Neha              3     Finance

# Concatination

In [21]:
df1=pd.DataFrame({"Name":["Rahul","Priya"],
                  "Salary":[45000,52000]})
df2=pd.DataFrame({"Name":["Aman","Neha"],
                  "Salary":[38000,75000]})

In [22]:
result=pd.concat([df1,df2],ignore_index=True)
result

    Name  Salary
0  Rahul   45000
1  Priya   52000
2   Aman   38000
3   Neha   75000

# Conactinating Horizontally

In [23]:
df1=pd.DataFrame({"Name":["Rahul","Priya"],
                  "Salary":[45000,52000]})
df2=pd.DataFrame({"Experience":[2,3],
                 "Department":["IT","HR"]})

In [24]:
result=pd.concat([df1,df2],axis=1)
result

    Name  Salary  Experience Department
0  Rahul   45000           2         IT
1  Priya   52000           3         HR