# Advance Filtering

In [1]:
import pandas as pd 
df=pd.read_csv(r"C:\Users\ankit\OneDrive\Desktop\employee_data.csv")
df

    Employee_ID    Name Department Gender  Salary  Experience  Performance
0          2001   Rahul         IT      M   45000           2           82
1          2002   Priya         HR      F   52000           3           91
2          2003    Aman    Finance      M   38000           1           68
3          2004    Neha         IT      F   75000           5           95
4          2005   Rohit      Sales      M   42000           2           76
5          2006  Simran         HR      F   61000           4           88
6          2007   Arjun    Finance      M   82000           6           93
7          2008   Kavya         IT      F   39000           1           72
8          2009   Vikas      Sales      M   68000           4           85
9          2010   Pooja         HR      F   47000           2           79
10         2011  Deepak    Finance      M   55000           3           87
11         2012   Nisha         IT      F   92000           7           97
12         2013  Manish      Sales      M   36000           1           65
13         2014    Riya         HR      F   78000           5           90
14         2015   Karan    Finance      M   43000           2           74
15         2016  Anjali         IT      F   64000           4           84
16         2017  Sachin      Sales      M   59000           3           81
17         2018   Meena         HR      F   35000           1           69
18         2019   Varun         IT      M   88000           6           92
19         2020    Isha    Finance      F   70000           5           89

# isin --Filter Multiple values

In [3]:
df[(df["Department"]=="IT")|(df["Department"]=="HR")]

    Employee_ID    Name Department Gender  Salary  Experience  Performance
0          2001   Rahul         IT      M   45000           2           82
1          2002   Priya         HR      F   52000           3           91
3          2004    Neha         IT      F   75000           5           95
5          2006  Simran         HR      F   61000           4           88
7          2008   Kavya         IT      F   39000           1           72
9          2010   Pooja         HR      F   47000           2           79
11         2012   Nisha         IT      F   92000           7           97
13         2014    Riya         HR      F   78000           5           90
15         2016  Anjali         IT      F   64000           4           84
17         2018   Meena         HR      F   35000           1           69
18         2019   Varun         IT      M   88000           6           92

Instead of that we can do this

In [5]:
df[df["Department"].isin(["IT","HR"])]

    Employee_ID    Name Department Gender  Salary  Experience  Performance
0          2001   Rahul         IT      M   45000           2           82
1          2002   Priya         HR      F   52000           3           91
3          2004    Neha         IT      F   75000           5           95
5          2006  Simran         HR      F   61000           4           88
7          2008   Kavya         IT      F   39000           1           72
9          2010   Pooja         HR      F   47000           2           79
11         2012   Nisha         IT      F   92000           7           97
13         2014    Riya         HR      F   78000           5           90
15         2016  Anjali         IT      F   64000           4           84
17         2018   Meena         HR      F   35000           1           69
18         2019   Varun         IT      M   88000           6           92

# between --Filter with range

In [6]:
df[df["Salary"].between(40000,70000)]

    Employee_ID    Name Department Gender  Salary  Experience  Performance
0          2001   Rahul         IT      M   45000           2           82
1          2002   Priya         HR      F   52000           3           91
4          2005   Rohit      Sales      M   42000           2           76
5          2006  Simran         HR      F   61000           4           88
8          2009   Vikas      Sales      M   68000           4           85
9          2010   Pooja         HR      F   47000           2           79
10         2011  Deepak    Finance      M   55000           3           87
14         2015   Karan    Finance      M   43000           2           74
15         2016  Anjali         IT      F   64000           4           84
16         2017  Sachin      Sales      M   59000           3           81
19         2020    Isha    Finance      F   70000           5           89

# Query

In [7]:
df[df["Salary"]>70000]

    Employee_ID   Name Department Gender  Salary  Experience  Performance
3          2004   Neha         IT      F   75000           5           95
6          2007  Arjun    Finance      M   82000           6           93
11         2012  Nisha         IT      F   92000           7           97
13         2014   Riya         HR      F   78000           5           90
18         2019  Varun         IT      M   88000           6           92

In [8]:
df.query("Salary>70000")

    Employee_ID   Name Department Gender  Salary  Experience  Performance
3          2004   Neha         IT      F   75000           5           95
6          2007  Arjun    Finance      M   82000           6           93
11         2012  Nisha         IT      F   92000           7           97
13         2014   Riya         HR      F   78000           5           90
18         2019  Varun         IT      M   88000           6           92

# String operation

In [10]:
# convert to lower case
df["Name"]=df["Name"].str.lower()
df["Name"]

0      rahul
1      priya
2       aman
3       neha
4      rohit
5     simran
6      arjun
7      kavya
8      vikas
9      pooja
10    deepak
11     nisha
12    manish
13      riya
14     karan
15    anjali
16    sachin
17     meena
18     varun
19      isha
Name: Name, dtype: str

In [12]:
# Convert to Upper Case
df["Name"]=df["Name"].str.upper()
df["Name"]

0      RAHUL
1      PRIYA
2       AMAN
3       NEHA
4      ROHIT
5     SIMRAN
6      ARJUN
7      KAVYA
8      VIKAS
9      POOJA
10    DEEPAK
11     NISHA
12    MANISH
13      RIYA
14     KARAN
15    ANJALI
16    SACHIN
17     MEENA
18     VARUN
19      ISHA
Name: Name, dtype: str

In [13]:
# Remove the space
df["Name"]=df["Name"].str.strip()
df["Name"]

0      RAHUL
1      PRIYA
2       AMAN
3       NEHA
4      ROHIT
5     SIMRAN
6      ARJUN
7      KAVYA
8      VIKAS
9      POOJA
10    DEEPAK
11     NISHA
12    MANISH
13      RIYA
14     KARAN
15    ANJALI
16    SACHIN
17     MEENA
18     VARUN
19      ISHA
Name: Name, dtype: str

In [ ]:
# To Find Name Conatining Any letter
df[df["Name"].str.contains('a',case=False)] # Case is for to ignore

    Employee_ID    Name Department Gender  Salary  Experience  Performance
0          2001   RAHUL         IT      M   45000           2           82
1          2002   PRIYA         HR      F   52000           3           91
2          2003    AMAN    Finance      M   38000           1           68
3          2004    NEHA         IT      F   75000           5           95
5          2006  SIMRAN         HR      F   61000           4           88
6          2007   ARJUN    Finance      M   82000           6           93
7          2008   KAVYA         IT      F   39000           1           72
8          2009   VIKAS      Sales      M   68000           4           85
9          2010   POOJA         HR      F   47000           2           79
10         2011  DEEPAK    Finance      M   55000           3           87
11         2012   NISHA         IT      F   92000           7           97
12         2013  MANISH      Sales      M   36000           1           65
13         2014    RIYA         HR      F   78000           5           90
14         2015   KARAN    Finance      M   43000           2           74
15         2016  ANJALI         IT      F   64000           4           84
16         2017  SACHIN      Sales      M   59000           3           81
17         2018   MEENA         HR      F   35000           1           69
18         2019   VARUN         IT      M   88000           6           92
19         2020    ISHA    Finance      F   70000           5           89

In [ ]:
# Name Starting with
df[df["Name"].str.startswith("A")] # In this we can not use case argument

    Employee_ID    Name Department Gender  Salary  Experience  Performance
2          2003    AMAN    Finance      M   38000           1           68
6          2007   ARJUN    Finance      M   82000           6           93
15         2016  ANJALI         IT      F   64000           4           84

In [ ]:
# Name Endswith
df[df["Name"].str.endswith("T")]

   Employee_ID   Name Department Gender  Salary  Experience  Performance
4         2005  ROHIT      Sales      M   42000           2           76

In [24]:
# To See the length
df["Length of Name"]=df["Name"].str.len()
df

,Employee_ID,Name,Department,Gender,Salary,Experience,Performance,Length of Name
0,2001,RAHUL,IT,M,45000,2,82,5
1,2002,PRIYA,HR,F,52000,3,91,5
2,2003,AMAN,Finance,M,38000,1,68,4
3,2004,NEHA,IT,F,75000,5,95,4
4,2005,ROHIT,Sales,M,42000,2,76,5
5,2006,SIMRAN,HR,F,61000,4,88,6
6,2007,ARJUN,Finance,M,82000,6,93,5
7,2008,KAVYA,IT,F,39000,1,72,5
8,2009,VIKAS,Sales,M,68000,4,85,5
9,2010,POOJA,HR,F,47000,2,79,5
10,2011,DEEPAK,Finance,M,55000,3,87,6
11,2012,NISHA,IT,F,92000,7,97,5
12,2013,MANISH,Sales,M,36000,1,65,6
13,2014,RIYA,HR,F,78000,5,90,4
14,2015,KARAN,Finance,M,43000,2,74,5
15,2016,ANJALI,IT,F,64000,4,84,6
16,2017,SACHIN,Sales,M,59000,3,81,6
17,2018,MEENA,HR,F,35000,1,69,5
18,2019,VARUN,IT,M,88000,6,92,5
19,2020,ISHA,Finance,F,70000,5,89,4

In [26]:
# To Repalce The Data
df["Department"]=df["Department"].str.replace('IT','Information Technology')
df

,Employee_ID,Name,Department,Gender,Salary,Experience,Performance,Length of Name
0,2001,RAHUL,Information Technology,M,45000,2,82,5
1,2002,PRIYA,HR,F,52000,3,91,5
2,2003,AMAN,Finance,M,38000,1,68,4
3,2004,NEHA,Information Technology,F,75000,5,95,4
4,2005,ROHIT,Sales,M,42000,2,76,5
5,2006,SIMRAN,HR,F,61000,4,88,6
6,2007,ARJUN,Finance,M,82000,6,93,5
7,2008,KAVYA,Information Technology,F,39000,1,72,5
8,2009,VIKAS,Sales,M,68000,4,85,5
9,2010,POOJA,HR,F,47000,2,79,5
10,2011,DEEPAK,Finance,M,55000,3,87,6
11,2012,NISHA,Information Technology,F,92000,7,97,5
12,2013,MANISH,Sales,M,36000,1,65,6
13,2014,RIYA,HR,F,78000,5,90,4
14,2015,KARAN,Finance,M,43000,2,74,5
15,2016,ANJALI,Information Technology,F,64000,4,84,6
16,2017,SACHIN,Sales,M,59000,3,81,6
17,2018,MEENA,HR,F,35000,1,69,5
18,2019,VARUN,Information Technology,M,88000,6,92,5
19,2020,ISHA,Finance,F,70000,5,89,4