# Date & Time

In [51]:
import pandas as pd
data=pd.DataFrame({"Name":["Rahul","Priya","Aman","Neha"],
                   "Joining Date":["2024-01-15","2023-06-20","2025-03-10","2022-11-05"]})
data.dtypes

Name            str
Joining Date    str
dtype: object

# Convert to datetime

In [52]:
data["Joining Date"]=pd.to_datetime(data["Joining Date"])
data.dtypes

Name                       str
Joining Date    datetime64[us]
dtype: object

# Extract the year

In [53]:
data["Year"]=data["Joining Date"].dt.year
data

    Name Joining Date  Year
0  Rahul   2024-01-15  2024
1  Priya   2023-06-20  2023
2   Aman   2025-03-10  2025
3   Neha   2022-11-05  2022

# Extract the month

In [54]:
data["Month"]=data["Joining Date"].dt.month
data

    Name Joining Date  Year  Month
0  Rahul   2024-01-15  2024      1
1  Priya   2023-06-20  2023      6
2   Aman   2025-03-10  2025      3
3   Neha   2022-11-05  2022     11

# Get The Month Name

In [55]:
data["Month Name"]=data["Joining Date"].dt.month_name()
data

    Name Joining Date  Year  Month Month Name
0  Rahul   2024-01-15  2024      1    January
1  Priya   2023-06-20  2023      6       June
2   Aman   2025-03-10  2025      3      March
3   Neha   2022-11-05  2022     11   November

# Extract Day

In [56]:
data["Day"]=data["Joining Date"].dt.day
data

    Name Joining Date  Year  Month Month Name  Day
0  Rahul   2024-01-15  2024      1    January   15
1  Priya   2023-06-20  2023      6       June   20
2   Aman   2025-03-10  2025      3      March   10
3   Neha   2022-11-05  2022     11   November    5

# **Find The Employees who joined after a date**

In [57]:
data[data["Joining Date"]>"2024-01-01"]

    Name Joining Date  Year  Month Month Name  Day
0  Rahul   2024-01-15  2024      1    January   15
2   Aman   2025-03-10  2025      3      March   10

# ** Find The Employee Who Joined in 2024**

In [58]:
data[data["Joining Date"].dt.year==2024]

    Name Joining Date  Year  Month Month Name  Day
0  Rahul   2024-01-15  2024      1    January   15

In [59]:
data[data["Joining Date"].dt.year.isin([2024,2025])]

    Name Joining Date  Year  Month Month Name  Day
0  Rahul   2024-01-15  2024      1    January   15
2   Aman   2025-03-10  2025      3      March   10

# **Pivot Table**

In [60]:
df=pd.read_csv(r"C:\Users\ankit\OneDrive\Desktop\employee_data.csv")
df

    Employee_ID    Name Department Gender  Salary  Experience  Performance
0          2001   Rahul         IT      M   45000           2           82
1          2002   Priya         HR      F   52000           3           91
2          2003    Aman    Finance      M   38000           1           68
3          2004    Neha         IT      F   75000           5           95
4          2005   Rohit      Sales      M   42000           2           76
5          2006  Simran         HR      F   61000           4           88
6          2007   Arjun    Finance      M   82000           6           93
7          2008   Kavya         IT      F   39000           1           72
8          2009   Vikas      Sales      M   68000           4           85
9          2010   Pooja         HR      F   47000           2           79
10         2011  Deepak    Finance      M   55000           3           87
11         2012   Nisha         IT      F   92000           7           97
12         2013  Manish      Sales      M   36000           1           65
13         2014    Riya         HR      F   78000           5           90
14         2015   Karan    Finance      M   43000           2           74
15         2016  Anjali         IT      F   64000           4           84
16         2017  Sachin      Sales      M   59000           3           81
17         2018   Meena         HR      F   35000           1           69
18         2019   Varun         IT      M   88000           6           92
19         2020    Isha    Finance      F   70000           5           89

In [61]:
pd.pivot_table(
    df,
    values='Salary',
    index='Department',
    aggfunc='mean'
)

                  Salary
Department
Finance     57600.000000
HR          54600.000000
IT          67166.666667
Sales       51250.000000

Two Level Anaylysis

In [62]:
pd.pivot_table(
    df,
    values="Salary",
    index="Department",
    columns=["Gender","Experience"],
    aggfunc=["mean","max"]
)

               mean                                                        \
Gender            F                                                     M
Experience        1        2        3        4        5        7        1
Department
Finance         NaN      NaN      NaN      NaN  70000.0      NaN  38000.0
HR          35000.0  47000.0  52000.0  61000.0  78000.0      NaN      NaN
IT          39000.0      NaN      NaN  64000.0  75000.0  92000.0      NaN
Sales           NaN      NaN      NaN      NaN      NaN      NaN  36000.0

                                       ...      max                    \
Gender                                 ...        F
Experience        2        3        4  ...        2        3        4
Department                             ...
Finance     43000.0  55000.0      NaN  ...      NaN      NaN      NaN
HR              NaN      NaN      NaN  ...  47000.0  52000.0  61000.0
IT          45000.0      NaN      NaN  ...      NaN      NaN  64000.0
Sales       42000.0  59000.0  68000.0  ...      NaN      NaN      NaN


Gender                              M
Experience        5        7        1        2        3        4        6
Department
Finance     70000.0      NaN  38000.0  43000.0  55000.0      NaN  82000.0
HR          78000.0      NaN      NaN      NaN      NaN      NaN      NaN
IT          75000.0  92000.0      NaN  45000.0      NaN      NaN  88000.0
Sales           NaN      NaN  36000.0  42000.0  59000.0  68000.0      NaN

[4 rows x 22 columns]

# Advance Merge And Join

** Merge When Column Names Are Different**

In [63]:
# Suppose
employee=pd.DataFrame({
    "Employee ID":[101,102,103],
    "Name":["Rahul","Priya","Aman"],
    "Dept ID":[1,2,1]
})

departments=pd.DataFrame({
    "Department ID":[1,2],
    "Department":["IT","HR"]
})

In [64]:
result=pd.merge(
    employee,
    departments,
    left_on="Dept ID",
    right_on="Department ID",
    how="left"
)
result

   Employee ID   Name  Dept ID  Department ID Department
0          101  Rahul        1              1         IT
1          102  Priya        2              2         HR
2          103   Aman        1              1         IT

# Merge Uisng Multiple Column

In [65]:
sales=pd.DataFrame({
    "Employee ID":[101,101,102],
    "Year":[2025,2026,2025],
    "Sales":[50000,65000,45000]
})

target=pd.DataFrame({
    "Employee ID":[101,101,102],
    "Year":[2025,2026,2025],
    "Target":[45000,60000,50000]
})

In [66]:
pd.merge(
    sales,
    target,
    on=["Employee ID","Year"],
    how="left"
)

   Employee ID  Year  Sales  Target
0          101  2025  50000   45000
1          101  2026  65000   60000
2          102  2025  45000   50000

What if both tables having the same column name?

In [67]:
sales=pd.DataFrame({
    "Employee ID":[101,101,102],
    "Year":[2025,2026,2025],
    "Sales":[50000,65000,45000]
})

target=pd.DataFrame({
    "Employee ID":[101,101,102],
    "Year":[2025,2026,2025],
    "Sales":[45000,60000,50000]
})

In [68]:
result=pd.merge(
    sales,
    target,
    on=["Employee ID","Year"],
    suffixes=["_customers","_festival"]
    
)
result

   Employee ID  Year  Sales_customers  Sales_festival
0          101  2025            50000           45000
1          101  2026            65000           60000
2          102  2025            45000           50000

join() is another methode especially when matching information is based on the index

In [69]:
df1=pd.DataFrame({
    "Name":["Rahul","Priya","Aman"],

},index=[101,102,103])

df2=pd.DataFrame({
    "Salary":[45000,52000,38000],

},index=[101,102,103])

In [70]:
result=df1.join(df2)
result

      Name  Salary
101  Rahul   45000
102  Priya   52000
103   Aman   38000