In [18]:
import pandas as pd
df=pd.DataFrame({
    "Name":["Amit","Ravi","Neha"],
    "Salary":[50000,60000,55000]
})
df

   Name  Salary
0  Amit   50000
1  Ravi   60000
2  Neha   55000

Index Change after filtering

In [19]:
df[df["Salary"]>50000].reset_index(drop=True)

   Name  Salary
0  Ravi   60000
1  Neha   55000

# To Set The Index to any column

In [20]:
data=pd.DataFrame({
    "Employee ID":[101,102,103],
    "Name":["Amit","Ravi","Neha"],
    "Salary":[50000,60000,55000]
})

In [21]:
df=data.set_index("Employee ID")
df

             Name  Salary
Employee ID
101          Amit   50000
102          Ravi   60000
103          Neha   55000

# nunique

In [31]:
df=pd.DataFrame({
    "Name":["Amit","Ravi","Amit","Neha","Ravi",None],
    "City":["Delhi","Mumbai","Delhi","Pune","Mumbai",None],
    "Department":["IT","HR","IT","Sales","HR",None]
})
df

   Name    City Department
0  Amit   Delhi         IT
1  Ravi  Mumbai         HR
2  Amit   Delhi         IT
3  Neha    Pune      Sales
4  Ravi  Mumbai         HR
5   NaN     NaN        NaN

To see unique city

By default nunique does not count nun value

In [32]:
df["City"].nunique()

3

if you want to count nan as a unique value

In [34]:
df.nunique(dropna=False)

Name          4
City          4
Department    4
dtype: int64

unique()=Actual Unique value

nunique()=Number of unique values

In [37]:
df["City"].unique()

<StringArray>
['Delhi', 'Mumbai', 'Pune', nan]
Length: 4, dtype: str

# value_counts()

In [40]:
df["City"].value_counts(ascending=True)

City
Pune      1
Delhi     2
Mumbai    2
Name: count, dtype: int64