In [70]:
import pandas as pd
df=pd.DataFrame({
    "Name":["A","B","C","D","E"],
    "Salary":[50000,70000,60000,90000,70000]

})
df

  Name  Salary
0    A   50000
1    B   70000
2    C   60000
3    D   90000
4    E   70000

# Rank()

In [71]:
# df["Rank"]=df["Salary"].rank(ascending=False)
# df

# Handiling ties with method

In [72]:
# 1.method="average"--default
df["Rank"]=df["Salary"].rank(ascending=False,
                             method="average")
df

  Name  Salary  Rank
0    A   50000   5.0
1    B   70000   2.5
2    C   60000   4.0
3    D   90000   1.0
4    E   70000   2.5

In [73]:
# 2.method="min"
df["Minimum"]=df["Salary"].rank(ascending=False,
                                method="min")
df

  Name  Salary  Rank  Minimum
0    A   50000   5.0      5.0
1    B   70000   2.5      2.0
2    C   60000   4.0      4.0
3    D   90000   1.0      1.0
4    E   70000   2.5      2.0

In [74]:
# 3.method="max"
df["Maximum"]=df["Salary"].rank(ascending=False,method="max")
df

  Name  Salary  Rank  Minimum  Maximum
0    A   50000   5.0      5.0      5.0
1    B   70000   2.5      2.0      3.0
2    C   60000   4.0      4.0      4.0
3    D   90000   1.0      1.0      1.0
4    E   70000   2.5      2.0      3.0

In [75]:
# 4.method="dense"
df["dense"]=df["Salary"].rank(ascending=False,method="dense")
df

  Name  Salary  Rank  Minimum  Maximum  dense
0    A   50000   5.0      5.0      5.0    4.0
1    B   70000   2.5      2.0      3.0    2.0
2    C   60000   4.0      4.0      4.0    3.0
3    D   90000   1.0      1.0      1.0    1.0
4    E   70000   2.5      2.0      3.0    2.0

In [76]:
# 5.method="first"
df["First"]=df["Salary"].rank(ascending=False,method="dense")
df

  Name  Salary  Rank  Minimum  Maximum  dense  First
0    A   50000   5.0      5.0      5.0    4.0    4.0
1    B   70000   2.5      2.0      3.0    2.0    2.0
2    C   60000   4.0      4.0      4.0    3.0    3.0
3    D   90000   1.0      1.0      1.0    1.0    1.0
4    E   70000   2.5      2.0      3.0    2.0    2.0

# **Advance Duplicate**

In [77]:
# Basic Duplicate 
df[df.duplicated()]

Empty DataFrame
Columns: [Name, Salary, Rank, Minimum, Maximum, dense, First]
Index: []

To Find In specific column

In [78]:
df[df.duplicated(subset=["Salary","Maximum"])]

  Name  Salary  Rank  Minimum  Maximum  dense  First
4    E   70000   2.5      2.0      3.0    2.0    2.0

keep="firts",keep="last",keep=False

In [79]:
df.duplicated(subset=["Salary"],keep="first")

0    False
1    False
2    False
3    False
4     True
dtype: bool

# To Remove The Duplicates

In [80]:
df.drop_duplicates(keep="first")

  Name  Salary  Rank  Minimum  Maximum  dense  First
0    A   50000   5.0      5.0      5.0    4.0    4.0
1    B   70000   2.5      2.0      3.0    2.0    2.0
2    C   60000   4.0      4.0      4.0    3.0    3.0
3    D   90000   1.0      1.0      1.0    1.0    1.0
4    E   70000   2.5      2.0      3.0    2.0    2.0

In [81]:
df.drop_duplicates(subset=["Salary"],keep="first")

  Name  Salary  Rank  Minimum  Maximum  dense  First
0    A   50000   5.0      5.0      5.0    4.0    4.0
1    B   70000   2.5      2.0      3.0    2.0    2.0
2    C   60000   4.0      4.0      4.0    3.0    3.0
3    D   90000   1.0      1.0      1.0    1.0    1.0

To keep that records that have no duplicates acoourance at all

In [84]:
result=df.drop_duplicates(subset=["Salary"],keep=False)
result

  Name  Salary  Rank  Minimum  Maximum  dense  First
0    A   50000   5.0      5.0      5.0    4.0    4.0
2    C   60000   4.0      4.0      4.0    3.0    3.0
3    D   90000   1.0      1.0      1.0    1.0    1.0

In [83]:
df.drop_duplicates(subset=["Salary"])

  Name  Salary  Rank  Minimum  Maximum  dense  First
0    A   50000   5.0      5.0      5.0    4.0    4.0
1    B   70000   2.5      2.0      3.0    2.0    2.0
2    C   60000   4.0      4.0      4.0    3.0    3.0
3    D   90000   1.0      1.0      1.0    1.0    1.0