# Date & Time

In [1]:
import pandas as pd
df=pd.DataFrame({"Employee":["Rahul","Priya","Aman","Neha","Rohit"],
                 "Joining Date":["2022-05-10","2023-08-15","2024-01-20","2024-07-05","2025-03-12"]
                 })
df

  Employee Joining Date
0    Rahul   2022-05-10
1    Priya   2023-08-15
2     Aman   2024-01-20
3     Neha   2024-07-05
4    Rohit   2025-03-12

In [2]:
df["Joining Date"]=pd.to_datetime(df["Joining Date"])
df.dtypes

Employee                   str
Joining Date    datetime64[us]
dtype: object

In [6]:
df["Year"]=df["Joining Date"].dt.year
df

  Employee Joining Date Month Name  Year
0    Rahul   2022-05-10        May  2022
1    Priya   2023-08-15     August  2023
2     Aman   2024-01-20    January  2024
3     Neha   2024-07-05       July  2024
4    Rohit   2025-03-12      March  2025

In [5]:
df["Month Name"]=df["Joining Date"].dt.month_name()
df

  Employee Joining Date Month Name
0    Rahul   2022-05-10        May
1    Priya   2023-08-15     August
2     Aman   2024-01-20    January
3     Neha   2024-07-05       July
4    Rohit   2025-03-12      March

In [7]:
df[df["Joining Date"].dt.year.isin([2024])]

  Employee Joining Date Month Name  Year
2     Aman   2024-01-20    January  2024
3     Neha   2024-07-05       July  2024

In [8]:
df[df["Joining Date"]>"2024-12-31"]

  Employee Joining Date Month Name  Year
4    Rohit   2025-03-12      March  2025