In [13]:
import pandas as pd
df=pd.read_csv(r"C:\Users\ankit\OneDrive\Desktop\pandas_class7_20_records.csv")
df

    Employee_ID    Name      City  Marks
0          1001    Amit    Delhi      78
1          1002   Rohit     delhi     85
2          1003   Sneha    Mumbai     92
3          1004   Priya     Delhi     67
4          1005   Karan     DELHI     88
5          1006    Neha   Mumbai      74
6          1007   Arjun      Pune     81
7          1008    Riya    Delhi      95
8          1009   Vikas    delhi      69
9          1010   Pooja    Mumbai     87
10         1011   Ankit     Delhi     76
11         1012   Rahul     Pune      83
12         1013  Simran     DELHI     91
13         1014  Manish   Mumbai      72
14         1015   Kavya     Delhi     89
15         1016    Aman    delhi      64
16         1017   Nisha      Pune     86
17         1018  Deepak     Delhi     78
18         1001    Amit    Delhi      78
19         1005   Karan     DELHI     88

Q1 Find the number of duplicate rows

In [14]:
df.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18     True
19     True
dtype: bool

In [15]:
df.duplicated().sum()

np.int64(2)

Q2 Remove Duplicates

In [16]:
df.drop_duplicates(inplace=True)

Q3 Convert the city column to lower case

In [17]:
df["City"]=df["City"].str.lower()
df

    Employee_ID    Name      City  Marks
0          1001    Amit    delhi      78
1          1002   Rohit     delhi     85
2          1003   Sneha    mumbai     92
3          1004   Priya     delhi     67
4          1005   Karan     delhi     88
5          1006    Neha   mumbai      74
6          1007   Arjun      pune     81
7          1008    Riya    delhi      95
8          1009   Vikas    delhi      69
9          1010   Pooja    mumbai     87
10         1011   Ankit     delhi     76
11         1012   Rahul     pune      83
12         1013  Simran     delhi     91
13         1014  Manish   mumbai      72
14         1015   Kavya     delhi     89
15         1016    Aman    delhi      64
16         1017   Nisha      pune     86
17         1018  Deepak     delhi     78

Q4 Remove The Extra Spaces from city column

In [18]:
df["City"]=df["City"].str.strip()
df

    Employee_ID    Name    City  Marks
0          1001    Amit   delhi     78
1          1002   Rohit   delhi     85
2          1003   Sneha  mumbai     92
3          1004   Priya   delhi     67
4          1005   Karan   delhi     88
5          1006    Neha  mumbai     74
6          1007   Arjun    pune     81
7          1008    Riya   delhi     95
8          1009   Vikas   delhi     69
9          1010   Pooja  mumbai     87
10         1011   Ankit   delhi     76
11         1012   Rahul    pune     83
12         1013  Simran   delhi     91
13         1014  Manish  mumbai     72
14         1015   Kavya   delhi     89
15         1016    Aman   delhi     64
16         1017   Nisha    pune     86
17         1018  Deepak   delhi     78

Q5 Replace "delhi" with "Delhi"

In [19]:
df["City"]=df["City"].replace({"delhi":"Delhi"
,"mumbai":"Mumbai","pune":"Pune"})
df

    Employee_ID    Name    City  Marks
0          1001    Amit   Delhi     78
1          1002   Rohit   Delhi     85
2          1003   Sneha  Mumbai     92
3          1004   Priya   Delhi     67
4          1005   Karan   Delhi     88
5          1006    Neha  Mumbai     74
6          1007   Arjun    Pune     81
7          1008    Riya   Delhi     95
8          1009   Vikas   Delhi     69
9          1010   Pooja  Mumbai     87
10         1011   Ankit   Delhi     76
11         1012   Rahul    Pune     83
12         1013  Simran   Delhi     91
13         1014  Manish  Mumbai     72
14         1015   Kavya   Delhi     89
15         1016    Aman   Delhi     64
16         1017   Nisha    Pune     86
17         1018  Deepak   Delhi     78

In [ ]:
df.to_csv(r"C:\Users\ankit\OneDrive\Desktop\Pandas.csv",index=False)

NameError: name 'df' is not defined