In [18]:
import pandas as pd
data={
    "Name":["Amit","Rohit","Sneha","Priya","Karan"],
    "Age":[20,21,19,None,20],
    "Marks":[78,85,None,67,88]
}
df=pd.DataFrame(data)
df

    Name   Age  Marks
0   Amit  20.0   78.0
1  Rohit  21.0   85.0
2  Sneha  19.0    NaN
3  Priya   NaN   67.0
4  Karan  20.0   88.0

In [19]:
df.loc[:,["Age"]]

    Age
0  20.0
1  21.0
2  19.0
3   NaN
4  20.0

In [20]:
df.loc[:,["Name","Marks"]]

    Name  Marks
0   Amit   78.0
1  Rohit   85.0
2  Sneha    NaN
3  Priya   67.0
4  Karan   88.0

In [21]:
df.head(3)

    Name   Age  Marks
0   Amit  20.0   78.0
1  Rohit  21.0   85.0
2  Sneha  19.0    NaN

In [22]:
df.iloc[0,2]

np.float64(78.0)

In [23]:
df.loc[0:2,["Name","Marks"]]

    Name  Marks
0   Amit   78.0
1  Rohit   85.0
2  Sneha    NaN

In [24]:
df[df["Marks"]>85]

    Name   Age  Marks
4  Karan  20.0   88.0

In [25]:
df[df["Age"]==20]

    Name   Age  Marks
0   Amit  20.0   78.0
4  Karan  20.0   88.0

In [26]:
df[(df["Marks"]>80) & (df["Age"]<=20)]

    Name   Age  Marks
4  Karan  20.0   88.0

In [27]:
df[(df["Marks"]>90)|(df["Marks"]<70)]

    Name  Age  Marks
3  Priya  NaN   67.0

In [28]:
df.rename(columns={"Marks":"Score","Age":"Current Age"},inplace=True)

In [29]:
df

    Name  Current Age  Score
0   Amit         20.0   78.0
1  Rohit         21.0   85.0
2  Sneha         19.0    NaN
3  Priya          NaN   67.0
4  Karan         20.0   88.0

In [30]:
df.sort_values("Score",ascending=False)

    Name  Current Age  Score
4  Karan         20.0   88.0
1  Rohit         21.0   85.0
0   Amit         20.0   78.0
3  Priya          NaN   67.0
2  Sneha         19.0    NaN

In [31]:
df.sort_values("Current Age")

    Name  Current Age  Score
2  Sneha         19.0    NaN
0   Amit         20.0   78.0
4  Karan         20.0   88.0
1  Rohit         21.0   85.0
3  Priya          NaN   67.0

In [32]:
df["City"]=["Delhi","Mumbai","Delhi","Pune","Delhi"]

In [33]:
df["City"].value_counts()

City
Delhi     3
Mumbai    1
Pune      1
Name: count, dtype: int64

In [35]:
df.isnull().sum()

Name           0
Current Age    1
Score          1
City           0
dtype: int64

In [37]:
df["Current Age"]=df["Current Age"].fillna(df["Current Age"].mean())
df

    Name  Current Age  Score    City
0   Amit         20.0   78.0   Delhi
1  Rohit         21.0   85.0  Mumbai
2  Sneha         19.0    NaN   Delhi
3  Priya         20.0   67.0    Pune
4  Karan         20.0   88.0   Delhi

In [38]:
df["Score"]=df["Score"].fillna(df["Score"].median())
df

    Name  Current Age  Score    City
0   Amit         20.0   78.0   Delhi
1  Rohit         21.0   85.0  Mumbai
2  Sneha         19.0   81.5   Delhi
3  Priya         20.0   67.0    Pune
4  Karan         20.0   88.0   Delhi

In [39]:
df.isna().sum()

Name           0
Current Age    0
Score          0
City           0
dtype: int64