In [1]:
import pandas as pd
df=pd.read_csv(r"C:\Users\ankit\OneDrive\Desktop\employee_data.csv")
df["Salary"]=df["Salary"].replace({45000:40000})
df

    Employee_ID    Name Department Gender  Salary  Experience  Performance
0          2001   Rahul         IT      M   40000           2           82
1          2002   Priya         HR      F   52000           3           91
2          2003    Aman    Finance      M   38000           1           68
3          2004    Neha         IT      F   75000           5           95
4          2005   Rohit      Sales      M   42000           2           76
5          2006  Simran         HR      F   61000           4           88
6          2007   Arjun    Finance      M   82000           6           93
7          2008   Kavya         IT      F   39000           1           72
8          2009   Vikas      Sales      M   68000           4           85
9          2010   Pooja         HR      F   47000           2           79
10         2011  Deepak    Finance      M   55000           3           87
11         2012   Nisha         IT      F   92000           7           97
12         2013  Manish      Sales      M   36000           1           65
13         2014    Riya         HR      F   78000           5           90
14         2015   Karan    Finance      M   43000           2           74
15         2016  Anjali         IT      F   64000           4           84
16         2017  Sachin      Sales      M   59000           3           81
17         2018   Meena         HR      F   35000           1           69
18         2019   Varun         IT      M   88000           6           92
19         2020    Isha    Finance      F   70000           5           89

In [2]:
def grade(Performance):
    if Performance>=90:
        return "A"
    elif Performance>=80:
        return "B"
    elif Performance>=70:
        return "C"
    else:
        return "D"

df["Grade"]=df["Performance"].apply(grade)
df

,Employee_ID,Name,Department,Gender,Salary,Experience,Performance,Grade
0,2001,Rahul,IT,M,40000,2,82,B
1,2002,Priya,HR,F,52000,3,91,A
2,2003,Aman,Finance,M,38000,1,68,D
3,2004,Neha,IT,F,75000,5,95,A
4,2005,Rohit,Sales,M,42000,2,76,C
5,2006,Simran,HR,F,61000,4,88,B
6,2007,Arjun,Finance,M,82000,6,93,A
7,2008,Kavya,IT,F,39000,1,72,C
8,2009,Vikas,Sales,M,68000,4,85,B
9,2010,Pooja,HR,F,47000,2,79,C
10,2011,Deepak,Finance,M,55000,3,87,B
11,2012,Nisha,IT,F,92000,7,97,A
12,2013,Manish,Sales,M,36000,1,65,D
13,2014,Riya,HR,F,78000,5,90,A
14,2015,Karan,Finance,M,43000,2,74,C
15,2016,Anjali,IT,F,64000,4,84,B
16,2017,Sachin,Sales,M,59000,3,81,B
17,2018,Meena,HR,F,35000,1,69,D
18,2019,Varun,IT,M,88000,6,92,A
19,2020,Isha,Finance,F,70000,5,89,B

In [3]:
def salary(Salary):
    if Salary < 40000:
        return "low"
    elif Salary <= 70000 :
        return "Medium"
    else:
        return "High"

df["Salary Category"]=df["Salary"].apply(salary)
df

,Employee_ID,Name,Department,Gender,Salary,Experience,Performance,Grade,Salary Category
0,2001,Rahul,IT,M,40000,2,82,B,Medium
1,2002,Priya,HR,F,52000,3,91,A,Medium
2,2003,Aman,Finance,M,38000,1,68,D,low
3,2004,Neha,IT,F,75000,5,95,A,High
4,2005,Rohit,Sales,M,42000,2,76,C,Medium
5,2006,Simran,HR,F,61000,4,88,B,Medium
6,2007,Arjun,Finance,M,82000,6,93,A,High
7,2008,Kavya,IT,F,39000,1,72,C,low
8,2009,Vikas,Sales,M,68000,4,85,B,Medium
9,2010,Pooja,HR,F,47000,2,79,C,Medium
10,2011,Deepak,Finance,M,55000,3,87,B,Medium
11,2012,Nisha,IT,F,92000,7,97,A,High
12,2013,Manish,Sales,M,36000,1,65,D,low
13,2014,Riya,HR,F,78000,5,90,A,High
14,2015,Karan,Finance,M,43000,2,74,C,Medium
15,2016,Anjali,IT,F,64000,4,84,B,Medium
16,2017,Sachin,Sales,M,59000,3,81,B,Medium
17,2018,Meena,HR,F,35000,1,69,D,low
18,2019,Varun,IT,M,88000,6,92,A,High
19,2020,Isha,Finance,F,70000,5,89,B,Medium

In [4]:
df["Gender"]=df["Gender"].map({"M":"Male","F":"Female"}).str.strip()
df

,Employee_ID,Name,Department,Gender,Salary,Experience,Performance,Grade,Salary Category
0,2001,Rahul,IT,Male,40000,2,82,B,Medium
1,2002,Priya,HR,Female,52000,3,91,A,Medium
2,2003,Aman,Finance,Male,38000,1,68,D,low
3,2004,Neha,IT,Female,75000,5,95,A,High
4,2005,Rohit,Sales,Male,42000,2,76,C,Medium
5,2006,Simran,HR,Female,61000,4,88,B,Medium
6,2007,Arjun,Finance,Male,82000,6,93,A,High
7,2008,Kavya,IT,Female,39000,1,72,C,low
8,2009,Vikas,Sales,Male,68000,4,85,B,Medium
9,2010,Pooja,HR,Female,47000,2,79,C,Medium
10,2011,Deepak,Finance,Male,55000,3,87,B,Medium
11,2012,Nisha,IT,Female,92000,7,97,A,High
12,2013,Manish,Sales,Male,36000,1,65,D,low
13,2014,Riya,HR,Female,78000,5,90,A,High
14,2015,Karan,Finance,Male,43000,2,74,C,Medium
15,2016,Anjali,IT,Female,64000,4,84,B,Medium
16,2017,Sachin,Sales,Male,59000,3,81,B,Medium
17,2018,Meena,HR,Female,35000,1,69,D,low
18,2019,Varun,IT,Male,88000,6,92,A,High
19,2020,Isha,Finance,Female,70000,5,89,B,Medium

In [5]:
def expertise(Experience):
    if Experience<2:
        return "Fresher"
    elif Experience<=4:
        return "Mid-Level"
    else:
        return "senior"

df["Experience Level"]=df["Experience"].apply(expertise)
df

,Employee_ID,Name,Department,Gender,Salary,Experience,Performance,Grade,Salary Category,Experience Level
0,2001,Rahul,IT,Male,40000,2,82,B,Medium,Mid-Level
1,2002,Priya,HR,Female,52000,3,91,A,Medium,Mid-Level
2,2003,Aman,Finance,Male,38000,1,68,D,low,Fresher
3,2004,Neha,IT,Female,75000,5,95,A,High,senior
4,2005,Rohit,Sales,Male,42000,2,76,C,Medium,Mid-Level
5,2006,Simran,HR,Female,61000,4,88,B,Medium,Mid-Level
6,2007,Arjun,Finance,Male,82000,6,93,A,High,senior
7,2008,Kavya,IT,Female,39000,1,72,C,low,Fresher
8,2009,Vikas,Sales,Male,68000,4,85,B,Medium,Mid-Level
9,2010,Pooja,HR,Female,47000,2,79,C,Medium,Mid-Level
10,2011,Deepak,Finance,Male,55000,3,87,B,Medium,Mid-Level
11,2012,Nisha,IT,Female,92000,7,97,A,High,senior
12,2013,Manish,Sales,Male,36000,1,65,D,low,Fresher
13,2014,Riya,HR,Female,78000,5,90,A,High,senior
14,2015,Karan,Finance,Male,43000,2,74,C,Medium,Mid-Level
15,2016,Anjali,IT,Female,64000,4,84,B,Medium,Mid-Level
16,2017,Sachin,Sales,Male,59000,3,81,B,Medium,Mid-Level
17,2018,Meena,HR,Female,35000,1,69,D,low,Fresher
18,2019,Varun,IT,Male,88000,6,92,A,High,senior
19,2020,Isha,Finance,Female,70000,5,89,B,Medium,senior

In [6]:
df.to_csv(r"C:\Users\ankit\OneDrive\Desktop\Pandas\eployee.csv",index=False)

In [7]:
df.groupby("Department")["Salary"].mean()

Department
Finance    57600.000000
HR         54600.000000
IT         66333.333333
Sales      51250.000000
Name: Salary, dtype: float64

In [8]:
df.groupby("Department")["Salary"].max()

Department
Finance    82000
HR         78000
IT         92000
Sales      68000
Name: Salary, dtype: int64

In [9]:
df.groupby("Department")["Salary"].min()

Department
Finance    38000
HR         35000
IT         39000
Sales      36000
Name: Salary, dtype: int64

In [10]:
df.groupby("Department")["Salary"].count()

Department
Finance    5
HR         5
IT         6
Sales      4
Name: Salary, dtype: int64

In [11]:
df.groupby("Department").agg({"Salary":["mean","max","min"],
                              "Performance":"mean",
                              "Experience":"mean",
                              "Employee_ID":"count"})

                  Salary               Performance Experience Employee_ID
                    mean    max    min        mean       mean       count
Department
Finance     57600.000000  82000  38000       82.20   3.400000           5
HR          54600.000000  78000  35000       83.40   3.000000           5
IT          66333.333333  92000  39000       87.00   4.166667           6
Sales       51250.000000  68000  36000       76.75   2.500000           4

In [12]:
result=df.groupby("Department").agg(
    Average_Salary=("Salary","mean"),
    Maximum_Salary=("Salary","max"),
    Minimum_Salary=("Salary","min"),
    Average_Performance=("Performance","mean"),
    Employee_Count=("Employee_ID","count")

)
result

,Average_Salary,Maximum_Salary,Minimum_Salary,Average_Performance,Employee_Count
Department,,,,,
Finance,57600.000000,82000,38000,82.20,5
HR,54600.000000,78000,35000,83.40,5
IT,66333.333333,92000,39000,87.00,6
Sales,51250.000000,68000,36000,76.75,4

In [13]:
result.to_csv(r"C:\Users\ankit\OneDrive\Desktop\Pandas\result.csv")

In [14]:
df[df["Department"].isin(["IT","Finance"])]

,Employee_ID,Name,Department,Gender,Salary,Experience,Performance,Grade,Salary Category,Experience Level
0,2001,Rahul,IT,Male,40000,2,82,B,Medium,Mid-Level
2,2003,Aman,Finance,Male,38000,1,68,D,low,Fresher
3,2004,Neha,IT,Female,75000,5,95,A,High,senior
6,2007,Arjun,Finance,Male,82000,6,93,A,High,senior
7,2008,Kavya,IT,Female,39000,1,72,C,low,Fresher
10,2011,Deepak,Finance,Male,55000,3,87,B,Medium,Mid-Level
11,2012,Nisha,IT,Female,92000,7,97,A,High,senior
14,2015,Karan,Finance,Male,43000,2,74,C,Medium,Mid-Level
15,2016,Anjali,IT,Female,64000,4,84,B,Medium,Mid-Level
18,2019,Varun,IT,Male,88000,6,92,A,High,senior
19,2020,Isha,Finance,Female,70000,5,89,B,Medium,senior

In [15]:
df[df["Salary"].between(50000,80000)]

,Employee_ID,Name,Department,Gender,Salary,Experience,Performance,Grade,Salary Category,Experience Level
1,2002,Priya,HR,Female,52000,3,91,A,Medium,Mid-Level
3,2004,Neha,IT,Female,75000,5,95,A,High,senior
5,2006,Simran,HR,Female,61000,4,88,B,Medium,Mid-Level
8,2009,Vikas,Sales,Male,68000,4,85,B,Medium,Mid-Level
10,2011,Deepak,Finance,Male,55000,3,87,B,Medium,Mid-Level
13,2014,Riya,HR,Female,78000,5,90,A,High,senior
15,2016,Anjali,IT,Female,64000,4,84,B,Medium,Mid-Level
16,2017,Sachin,Sales,Male,59000,3,81,B,Medium,Mid-Level
19,2020,Isha,Finance,Female,70000,5,89,B,Medium,senior

In [16]:
df[df["Performance"].between(80,90)]

,Employee_ID,Name,Department,Gender,Salary,Experience,Performance,Grade,Salary Category,Experience Level
0,2001,Rahul,IT,Male,40000,2,82,B,Medium,Mid-Level
5,2006,Simran,HR,Female,61000,4,88,B,Medium,Mid-Level
8,2009,Vikas,Sales,Male,68000,4,85,B,Medium,Mid-Level
10,2011,Deepak,Finance,Male,55000,3,87,B,Medium,Mid-Level
13,2014,Riya,HR,Female,78000,5,90,A,High,senior
15,2016,Anjali,IT,Female,64000,4,84,B,Medium,Mid-Level
16,2017,Sachin,Sales,Male,59000,3,81,B,Medium,Mid-Level
19,2020,Isha,Finance,Female,70000,5,89,B,Medium,senior

In [18]:
df.query("Salary>60000")

,Employee_ID,Name,Department,Gender,Salary,Experience,Performance,Grade,Salary Category,Experience Level
3,2004,Neha,IT,Female,75000,5,95,A,High,senior
5,2006,Simran,HR,Female,61000,4,88,B,Medium,Mid-Level
6,2007,Arjun,Finance,Male,82000,6,93,A,High,senior
8,2009,Vikas,Sales,Male,68000,4,85,B,Medium,Mid-Level
11,2012,Nisha,IT,Female,92000,7,97,A,High,senior
13,2014,Riya,HR,Female,78000,5,90,A,High,senior
15,2016,Anjali,IT,Female,64000,4,84,B,Medium,Mid-Level
18,2019,Varun,IT,Male,88000,6,92,A,High,senior
19,2020,Isha,Finance,Female,70000,5,89,B,Medium,senior

In [23]:
df.query("Department=='IT' & Performance>=90")

,Employee_ID,Name,Department,Gender,Salary,Experience,Performance,Grade,Salary Category,Experience Level
3,2004,Neha,IT,Female,75000,5,95,A,High,senior
11,2012,Nisha,IT,Female,92000,7,97,A,High,senior
18,2019,Varun,IT,Male,88000,6,92,A,High,senior